### ISSUE TITLE
ImportError: No module named 'gym.monitoring'

### ISSUE THREAD

**Issue by zhan0903** [lerrel/rllab-adv#3]
When running this code, there is a problem showed in the title. I use my MacBook to run it with the newest operating system version, how to fix it? Thanks.

**Comment by jerinphilip** [comment]
https://github.com/lerrel/gym-adv/tree/master/gym/monitoring

His fork has the monitoring module, as you can see above. Use it.

**Comment by zhan0903** [comment]
Thanks. It works. By the way, the gym-adv is just the gym environment library or it includes the adv algorithms already and no need to use rllab-adv code anymore? Thanks.

**Comment by jerinphilip** [comment]
`gym-adv` has modifications to the agent to take in different parameters, the paper discusses modifications so adversary can have superpowers, those features are implemented there I think.

The algorithms are in this repo.

**Comment by zhan0903** [comment]
Thanks. I have a question: the author gives an example: "python adversarial/scripts/train_adversary.py --env InvertedPendulumAdv-v1 --folder ~/rllab-adv/results". The parameter "InvertedPendulumAdv-v1" comes from where? How about other envs? Where can I find other env's definition?

**Comment by jerinphilip** [comment]
`envs` are in `gym-adv`.

**Comment by zhan0903** [comment]
Thanks. I ran the example, but no cartoon came up, only text result showing on the terminal. How to see the algorithm result in the animation?

**Comment by jerinphilip** [comment]
`viz_results.py`, if I remember correctly.

**Comment by zhan0903** [comment]
Thanks, but that visualize the result only.

**Comment by zhan0903** [comment]
It seems this repo don't include the RARL framework/algorithm implementation, just provide how to train adversary?

**Comment by TheScott463** [comment]
Just tried to get this working. but I get this error:
File "enjoy-adv.py", line 33, in <module>
    from gym.monitoring import VideoRecorder
ImportError: No module named monitoring

Then trying to pip install -U gym-adv
I get:
> pip install -U gym-adv
Collecting gym-adv
  Could not find a version that satisfies the requirement gym-adv (from versions: )
No matching distribution found for gym-adv
--------------------

Advice?

This issue popped up at:
...\rl-attack> python enjoy-adv.py --env Breakout --noisy --mode
l-dir ./data/Breakout/model-173000 --video ./Breakout.mp4
Traceback (most recent call last):
  File "enjoy-adv.py", line 33, in <module>
    from gym.monitoring import VideoRecorder
ImportError: No module named monitoring

**Comment by mumuyanyan** [comment]
how to do
